version: '2.0'
services:

  app:
    build:
      args:
        - ENV=prod
      context: ./env/app/
    image: go-app
    container_name: go-app
    networks:
      app_net:
        ipv4_address: 192.168.0.11
    ports:
      - "8080:8080"
    restart: always

  nginx:
    build:
      context: ./env/nginx/
    image: nginx
    container_name: nginx
    tty: true
    networks:
      app_net:
        ipv4_address: 192.168.0.10
    ports:
      - "80:80"
      - "443:443"
    restart: always

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
