---
- name: Install Docker/Git
  hosts: docker
  become: true

  tasks:
    - name: Checking packages has been installed
      apt:
        name:
        - python
        - ansible
        state: present
      tags: [docker]
      when: ansible_os_family == 'Ubuntu'        
    
    - name: Install Docker
      package:
        name:    
        - docker.io
        state: latest 
        update_cache: yes
      
    - name: Install Docker Compose
      package:
        name:    
        - docker-compose
        state: latest 
        update_cache: yes
 
    - name: Install Git
      package:
        name:    
        - git
        state: latest 
        update_cache: yes
 
    - name: Install Git Flow
      package:
        name:    
        - git-flow
        state: latest 
        update_cache: yes
 
    - name: Enable Docker.io
      command: systemctl enable docker.io

    - name: Start Docker.io
      command: systemctl start docker.io

    - name: Check Status Docker.io
      command: systemctl status docker.io
